# Generated by Django 3.1.2 on 2020-10-26 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('q_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='answer_s',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='t_question',
            new_name='text_question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='temper',
            new_name='type_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_s',
            field=models.CharField(default=2, max_length=128, verbose_name='ответ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='зарегестрирован'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='отредактирован'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='q_info.question', verbose_name='ответ для вопроса'),
        ),
    ]
