# Generated by Django 3.1.2 on 2020-10-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_info', '0002_auto_20201026_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='q_info.Question'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный')], max_length=128, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='q_info.User'),
        ),
    ]
