# Generated by Django 3.1.2 on 2020-10-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_info', '0003_auto_20201026_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='questions',
            field=models.ManyToManyField(blank=True, to='q_info.Question'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='users',
            field=models.ManyToManyField(blank=True, to='q_info.User'),
        ),
    ]
