# Generated by Django 3.1.2 on 2020-10-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('q_info', '0004_auto_20201026_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='questions',
            field=models.ManyToManyField(blank=True, to='q_info.Question', verbose_name='назначенные вопросы'),
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='users',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='q_info.user', verbose_name='назначенные пользователи'),
        ),
    ]
